### ISSUE TITLE
Implement modal window

### ISSUE THREAD

**Issue by tomaskourim** [mild-blue/tasks#3]
Úkolem je doimplementovat modální okno v app.component.html. Modální okno se otevře po zmáčknutí tlačítka "Open modal", které tam už je. Modální okno musí být implementováno jako separátní Angular komponenta (která už v repozitáři je). Stisknutím tlačítka s křížkem se modální okno zavře. Vzhled modálního okna musí splňovat design:

![image](https://user-images.githubusercontent.com/50045455/145052881-07d69609-6750-48e9-ac45-a0436466b3df.png)

Pro snadnější odečtení barev, fontu a velikostí je design k dispozici zde: https://xd.adobe.com/view/3bc06cf5-25ec-4781-8457-5a92e9639224-6e93/.

**Comment by NotLubo** [comment]
Ahojte, spravil som pull request ktorý čaká na code review. Ak sa vám bude kód páčiť rád ho s vami prediskutujem pri calle.
